spring.application.name=invoicing-service
spring.grpc.server.port=9092
spring.grpc.server.reflection.enabled=true
spring.grpc.server.security.enabled=false
spring.grpc.server.security.certificate-chain=
spring.grpc.server.security.private-key=
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
