spring.application.name=usage-ingestion-service
spring.grpc.server.port=9090
spring.grpc.server.reflection.enabled=true
spring.grpc.server.security.enabled=false
spring.grpc.server.security.certificate-chain=
spring.grpc.server.security.private-key=
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
billing.rating.host=localhost
billing.rating.port=9091
billing.rating.tls.enabled=false
billing.rating.tls.trust-cert=
billing.rating.timeout-ms=1200
billing.invoicing.host=localhost
billing.invoicing.port=9092
billing.invoicing.tls.enabled=false
billing.invoicing.tls.trust-cert=
billing.invoicing.timeout-ms=1200
billing.fail-on-rating-error=false
billing.fail-on-invoicing-error=false
